// This function was generated by a machine learning model by OpenAI (ChatGPT),
// in a sort of "pair programming" session on December 3, 2022. It took a few
// iterations where I pointed out bugs, but the bot fixed all the mistakes as
// I pointed them out. It actually generated the SVG <path> tags as strings
// but I refactored it to only return the angles, which I then apply to tags.
function clockArms(hour, minute) {
	const hourAngle = ((hour + minute/60) / 12) * 360;
	const minuteAngle = (minute / 60) * 360;
	return {hourAngle, minuteAngle};
}


async function itemPageMain() {
	const {repoID, rowID} = parseURIPath()

	const results = await app.SearchItems({
		repo: repoID,
		row_id: [ rowID ],
		related: 1,
		with_size: true,
		limit: 1
	});
	
	console.log("RESULT:", results);
	
	const item = results.items[0];
	const dt = DateTime.fromISO(item.timestamp, { setZone: true });
	
	// items without a timestamp (albums, chat threads) have no time to draw
	const {hourAngle, minuteAngle} = item.timestamp ? clockArms(dt.hour, dt.minute) : {hourAngle: 0, minuteAngle: 0};
	$('#time .hour-hand').setAttribute('transform', `rotate(${hourAngle} 12 12)`);
	$('#time .minute-hand').setAttribute('transform', `rotate(${minuteAngle} 12 12)`);
	
	$('#item-id').innerText = item.id;

	// fork: developer debug panel (?debug=1 turns it on and remembers it; ?debug=0 turns it off)
	const debugParam = new URLSearchParams(location.search).get('debug');
	if (debugParam === '0') { try { localStorage.removeItem('tlz_debug'); } catch {} }
	else if (debugParam) { try { localStorage.setItem('tlz_debug', '1'); } catch {} }
	let debugOn = false;
	try { debugOn = localStorage.getItem('tlz_debug') === '1'; } catch {}
	if (debugOn) {
		renderItemDebug(repoID, item.id).catch(err => console.error("item debug panel:", err));
	}
	renderItemGraph(repoID, item.id).catch(err => console.error("item graph:", err));

	// download button
	// server may need to create a synthetic file for download if it's not a data file already
	$('#download-item').href = `/repo/${repoID}/dl/${item.id}`;
	$('#download-item').download = item.filename || ""; // crucial to avoid in-page nav

	let itemContentEl = itemContentElement(item, { autoplay: true });
	if (itemContentEl) {
		if (itemContentEl.dataset.contentType == "text") {
			// set font size relative to length of text, with bounds (20-100px) (the slope is somewhat arbitrary)
			// TODO: consider viewport size too (if approx. text space is length * fontSize, maybe a ratio to screen width * height?)
			// TODO: then re-compute on window resize
			itemContentEl.classList.add('item-content-text');
			const size = item.size || item.data_text?.length;
			const fontSize = Math.min(3500 * (1/size) + 20, 100);
			itemContentEl.style.fontSize = `${fontSize}px`;

			const card = document.createElement('div');
			card.classList.add('card');
			card.appendChild(itemContentEl);
			itemContentEl = card;
		}

		$('#item-content').append(itemContentEl);
	}

	if (item.entity) {
		$('#primary-entities').classList.remove('d-none');

		const display = entityDisplayNameAndAttr(item.entity);
		$('#item-owner-name').innerText = display.name;
		$('#item-owner-picture').innerHTML = avatar(true, item.entity);
		$('#item-owner-attribute').innerText = display.attribute;
		$('#entity-link').href = `/entities/${repoID}/${item.entity.id}`;
	}

	const tsDisplay = itemTimestampDisplay(item);
	if (tsDisplay.dateWithWeekday) {
		$('#item-date').innerText = tsDisplay.dateWithWeekday;
		$('#item-relative-time').innerText = dt.toRelative();
	} else {
		$('#item-date').parentElement.remove();
		$('#item-relative-time').remove();
	}
	if (tsDisplay.time) {
		$('#item-time').innerText = tsDisplay.timeWithZone;
	} else {
		$('#item-time').parentElement.remove();
	}

	const itemClass = tlz.itemClassIconAndLabel(item);
	$('#item-class-icon').innerHTML = itemClass.icon;
	$('#item-class-label').innerText = itemClass.label;

	if (item.data_type?.startsWith("image/")) {
		$('#item-type-label').innerText = "picture";
	} else if (item.data_type?.startsWith("video/")) {
		$('#item-type-label').innerText = "video";
	} else if (item.data_type?.startsWith("audio/")) {
		$('#item-type-label').innerText = "recording";
	} else if (item.data_type?.startsWith("text/")) {
		$('#item-type-label').innerText = "document";
	}

	if (item.original_path) {
		$('#item-original-path').innerText = item.original_path;
	} else if (item.filename) {
		$('#item-original-path').innerText = item.filename;
	} else {
		$('#item-original-path').parentElement.remove();
	}
	if (item.size) {
		$('#item-size').innerText = humanizeBytes(item.size);
	} else {
		$('#item-size').parentElement.remove();
	}
	if (item.data_type) {
		$('#item-media-type').innerText = item.data_type;
	} else {
		$('#item-media-type').parentElement.remove();
	}
	if (item.original_id) {
		$('#item-original-id').innerText = item.original_id;
		$('#item-original-id').parentNode.classList.remove('d-none');
	}
	if (item.original_location) {
		$('#item-original-location').innerText = item.original_location;
	} else {
		$('#item-original-location').parentElement.remove();
	}
	if (item.intermediate_location) {
		$('#item-intermediate-location').innerText = item.intermediate_location;
	} else {
		$('#item-intermediate-location').parentElement.remove();
	}
	if (item.latitude || item.longitude || item.altitude) {
		let coord = "";
		if (item.latitude) {
			coord = item.latitude.toFixed(5);
		}
		if (item.longitude) {
			if (coord) {
				coord += ", "
			}
			coord += item.longitude.toFixed(5);
		}
		$('#item-coordinate').innerText = coord;
	} else {
		$('#item-coordinate').parentElement.remove();
	}
	if (item.coordinate_uncertainty) {
		$('#item-coordinate-uncertainty').innerText = item.coordinate_uncertainty;
	} else {
		$('#item-coordinate-uncertainty').parentElement.remove();
	}
	if (item.altitude) {
		$('#item-altitude').innerText = Math.round(item.altitude * 3.28084) + " ft";
	} else {
		$('#item-altitude').parentElement.remove();
	}
	$('#item-stored').innerText = DateTime.fromISO(item.stored, { setZone: true }).toLocaleString(DateTime.DATETIME_MED_WITH_SECONDS);

	$('#data-source-icon').style.backgroundImage = `url('/ds-image/${item.data_source_name}')`;
	$('#data-source-title').innerText = item.data_source_title;

	// only show minimap if big map is not displayed
	if (!$('.map-container') && item.latitude && item.longitude) {
		const mapElem = cloneTemplate('#map-container');
		mapElem.classList.add('ratio-4x3');

		const minimapRenderFn = function() {
			const marker = new mapboxgl.Marker().setLngLat([item.longitude, item.latitude]);
			tlz.map.dragRotate.disable();
			tlz.map.tl_addMarker(marker);
			tlz.map.flyTo({
				center: [item.longitude, item.latitude],
				zoom: 13
			});
		};

		tlz.map.tl_containers.set(mapElem, minimapRenderFn);

		$('#minimap-container').classList.remove('d-none');
		$('#minimap-container').append(mapElem);
	}



	// TODO: see similar code in items.js -- make this standard somehow? (refactor)
	if (item.related) {
		for (let rel of item.related) {
			if ((rel.label == 'attachment' || rel.label == 'quotes' || rel.label == 'in_collection') && rel.to_item) {
				const attachTpl = cloneTemplate('#tpl-attachment');
				const labels = { attachment: 'Attached', quotes: 'Quotes / shares', in_collection: 'In collection' };

				const attachmentElem = itemContentElement(rel.to_item, { thumbnail: true });
				$('.card-img-bottom', attachTpl).appendChild(attachmentElem);

				$('.card-body', attachTpl).innerHTML = `
					<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-paperclip" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
						<path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
						<path d="M15 7l-6.5 6.5a1.5 1.5 0 0 0 3 3l6.5 -6.5a3 3 0 0 0 -6 -6l-6.5 6.5a4.5 4.5 0 0 0 9 9l6.5 -6.5"></path>
					</svg>
					${labels[rel.label]}`;
				
				$('a.card-link', attachTpl).href = `/items/${repoID}/${rel.to_item.id}`;

				$('#related-items').append(attachTpl);
				$('#related-items-container').classList.remove('d-none');

			} else if ((rel.label == 'sent' || rel.label == 'cc') && rel.to_entity) {
				$('#primary-entities').classList.remove('d-none');
				$('#related-entities').classList.remove('d-none');
				$('#related-entities-sent-to').classList.remove('d-none');

				const entTpl = cloneTemplate('#tpl-related-entity');
				
				$('.entity-picture', entTpl).innerHTML = avatar(true, rel.to_entity, 'avatar-xs');

				const entityDisplay = entityDisplayNameAndAttr(rel.to_entity);
				$('.entity-name', entTpl).innerText = entityDisplay.name;
				$('.entity-attr', entTpl).innerText = entityDisplay.attribute;
				entTpl.href = `/entities/${repoID}/${rel.to_entity.id}`;

				$('#related-entities-included').before(entTpl);

			} else if (rel.label == 'includes' && rel.to_entity) {
				// show the entity in the list on the sidebar
				$('#related-entities').classList.remove('d-none');
				$('#related-entities-included').classList.remove('d-none');
				const entTpl = cloneTemplate('#tpl-included-entity');
				$('.entity-picture', entTpl).innerHTML = avatar(true, rel.to_entity, 'avatar-xs');
				const entityDisplay = entityDisplayNameAndAttr(rel.to_entity);
				$('.entity-name', entTpl).innerText = entityDisplay.name;
				$('.entity-attr', entTpl).innerText = entityDisplay.attribute;
				// TODO: instead of going to the entity page, open a modal with more relationship details
				entTpl.href = `/entities/${repoID}/${rel.to_entity.id}`;

				function addCircle(centerX, centerY, sizeX, sizeY) {
					const boxEl = document.createElement('div');
					boxEl.id = `face-circle-rel-${rel.relationship_id}`;
					boxEl.classList.add('face-circle', 'd-none');
					boxEl.style.width = `${sizeX*100}%`;
					boxEl.style.height = `${sizeY*100}%`;
					boxEl.style.left = `${(centerX-sizeX/2)*100}%`
					boxEl.style.bottom = `${(centerY-sizeY/2)*100}%`; // NOTE: Apple's y-coord is from the bottom, not top!!
					boxEl.innerText = rel.to_entity.name || "unknown";
					$('#item-content').append(boxEl);

					// show the face circle when the name is hovered in the sidebar
					entTpl.onmouseover = function() {
						boxEl.classList.remove('d-none');
					};
					entTpl.onmouseout = function() {
						boxEl.classList.add('d-none');
					};
				}

				// then, if we have face detection info, show it on hover of their name
				// (if not face directly, "body detection" will work also)
				if (rel.metadata?.["Center X"] && rel.metadata?.["Center Y"] && rel.metadata?.["Size"]) {
					// small faces/outlines are harder to see, so we want those to appear a little larger,
					// whereas larger ones don't need to be scaled up as much
					const sizeScaled = rel.metadata["Size"] * (rel.metadata["Size"] > 0.05 ? 2 : 4);
					addCircle(rel.metadata["Center X"], rel.metadata["Center Y"], sizeScaled, sizeScaled);
				} else if (rel.metadata?.["Body center X"] && rel.metadata?.["Body center Y"] && rel.metadata?.["Body width"] && rel.metadata?.["Body height"]) {
					addCircle(rel.metadata["Body center X"], rel.metadata["Body center Y"], rel.metadata?.["Body width"], rel.metadata?.["Body height"])
				}

				$('#related-entities').append(entTpl);
				$('#primary-entities').classList.remove('d-none');
				if (!item.owner) {
					$('#related-entities').classList.add('border-top-0');
					$('#entity-link').classList.add('d-none');
				}
			}
		}
	}

	for (const key in item.metadata) {
		const tpl = cloneTemplate('#tpl-metadata');
		$('.datagrid-title', tpl).innerText = key;
		$('.datagrid-content', tpl).innerText = item.metadata[key];
		$('#item-metadata').append(tpl);
	}

	// For images, see if there is a motion photo associated with it
	if (item.data_type?.startsWith("image/")) {

		function renderMotionPhoto(videoSrc) {
			const video = document.createElement('video');
			video.classList.add('invisible','position-absolute'); // prevent empty space that gets shifted around during load

			// apparently canplay/canplaythrough fire multiple times if the video loops or we change the currentTime property
			let canPlay = false;
			video.addEventListener('canplay', e => {
				if (canPlay) return;
				canPlay = true;

				$('#item-content .thumbhash-container')?.classList?.add('d-none');
				$$('#item-content .content').forEach(elem => elem.classList.add('d-none')); // multiple .content elems? yes, in case a thumbhash is used with an image
				video.classList.remove('invisible', 'position-absolute');
				video.classList.add('fade-in');
				setTimeout(function() {
					video.classList.remove('fade-in');
				}, 1000);
				const tpl = cloneTemplate('#tpl-motionpicture');
				$('#item-content').append(tpl);
				video.muted = true; // for some reason, Chrome ignores the "muted" attribute, might be a bug: https://stackoverflow.com/a/51189390
				video.play();
			});
			video.addEventListener('error', (event, err) => {
				console.error("loading video:", event, err);
				video.remove();
			});

			video.setAttribute("controls", "");
			video.setAttribute("loop", "");
			video.setAttribute("autoplay", "");
			video.setAttribute("muted", "");
			video.src = videoSrc;
			
			$('#item-content').prepend(video);
		}

		// we can avoid another DB lookup if we just give back some info we already have
		const query = new URLSearchParams({
			data_file: item.data_file || ""
		});

		// look for a related item labeled 'motion' that might already be known;
		// giving the server this hint could save a DB query
		if (item.related) {
			for (const rel of item.related) {
				if (rel.label != 'motion') {
					continue;
				}
				query.set("hint", rel?.to_item?.data_file);
				const mpSrc = `/repo/${repoID}/motion-photo/${item.id}?${query.toString()}`;
				renderMotionPhoto(mpSrc);
				return;
			}
		}

		renderMotionPhoto(`/repo/${repoID}/motion-photo/${item.id}?${query.toString()}`);
	}
}

// TODO: The still photo of Samsung Live Photos is apparently the last frame of the embedded video.
// See: https://github.com/photoprism/photoprism/issues/439#issuecomment-1691477054
// This can make for a nice transition effect like what Google Photos does.

// toggle motion picture or still photo
on('click', '.motionpic-controls .icon-tabler-player-pause', e => {
	const pauseButton = e.target.closest('a');
	const playButton = $('.icon-tabler-player-play', pauseButton.parentElement);
	pauseButton.classList.add('d-none');
	playButton.classList.remove('d-none');
	$('#item-content video').classList.add('d-none');
	$$('#item-content .content').forEach(elem => elem.classList.remove('d-none')); // multiple? yes, in case a thumbhash is used with an image
	$('#item-content .thumbhash-container')?.classList?.remove('d-none');
	$('#item-content video').pause();
});
on('click', '.motionpic-controls .icon-tabler-player-play', e => {
	const playButton = e.target.closest('a');
	const pauseButton = $('.icon-tabler-player-pause', playButton.parentElement);
	playButton.classList.add('d-none');
	pauseButton.classList.remove('d-none');
	$('#item-content video').play();
	$('#item-content video').classList.remove('d-none');
	$$('#item-content .content').forEach(elem => elem.classList.add('d-none'));
	$('#item-content .thumbhash-container')?.classList?.add('d-none');
});


// renderItemDebug fetches the item-debug endpoint and renders every section as a
// collapsible block of raw JSON, with links to the data file, the Immich asset and
// related items/entities. Developer tooling; enabled per browser with ?debug=1.
async function renderItemDebug(repoID, itemID) {
	const d = await app.ItemDebug({ repo: repoID, item_id: Number(itemID) });
	const root = $('#item-debug');
	root.classList.remove('d-none');
	$('#item-debug-body').innerHTML = '';
	const section = (key, title, value, open) => {
		if (value == null || (Array.isArray(value) && value.length == 0) || (typeof value == 'object' && !Array.isArray(value) && Object.keys(value).length == 0)) return;
		const det = document.createElement('details');
		det.dataset.section = key;
		if (open) det.open = true;
		const sum = document.createElement('summary');
		sum.className = 'fw-bold';
		sum.textContent = title;
		det.append(sum);
		const pre = document.createElement('pre');
		pre.className = 'small mb-2';
		pre.style.whiteSpace = 'pre-wrap';
		pre.textContent = JSON.stringify(value, null, 2);
		det.append(pre);
		$('#item-debug-body').append(det);
		return det;
	};
	const links = document.createElement('div');
	links.className = 'mb-2 small';
	const link = (href, text) => { const a = document.createElement('a'); a.href = href; a.target = '_blank'; a.textContent = text; a.className = 'me-3'; links.append(a); };
	link(`/api/item-debug?repo=${encodeURIComponent(repoID)}&item_id=${itemID}`, 'raw JSON');
	if (d.data_file) link(d.data_file.serve_url, 'data file');
	if (d.immich?.web_url) link(d.immich.web_url, 'open in Immich');
	if (d.immich?.original_url) link(d.immich.original_url, 'Immich original');
	for (const e of d.entities || []) link(`/entities/${repoID}/${e.id}`, `entity ${e.id}: ${e.name || e.type}`);
	for (const id of Object.keys(d.items_referenced || {})) link(`/items/${repoID}/${id}?debug=1`, `item ${id}`);
	$('#item-debug-body').append(links);
	if (d.warnings?.length) {
		const w = document.createElement('div'); w.className = 'alert alert-warning py-1 small'; w.textContent = d.warnings.join('; '); $('#item-debug-body').append(w);
	}
	section('summary', `${d.classification || '(no class)'} from ${d.data_source}`, { classification: d.classification, data_source: d.data_source, repo_dir: d.repo_dir, generated: d.generated }, false);
	section('item', 'items row (as stored)', d.item, true);
	section('owner', 'owner (attribute -> entity)', d.owner, true);
	section('edges_out', `relationships out (${(d.edges_out||[]).length})`, d.edges_out, true);
	section('edges_in', `relationships in (${(d.edges_in||[]).length})`, d.edges_in, true);
	section('items_referenced', 'items at the other end of edges', d.items_referenced, false);
	section('entities', 'entities at the other end of edges (with attributes)', d.entities, false);
	section('data_file', 'data file on disk', d.data_file, true);
	section('immich', 'Immich asset', d.immich, true);
	section('link_fetch', 'link fetch cache entry', d.link_fetch, true);
	section('thumbnail', 'thumbnail cache', d.thumbnail, false);
	section('job', 'import job', d.job, false);
}


// ---- fork: relationship graph ------------------------------------------------------------

const graphColors = {
	message: '#206bc4', social: '#4299e1', media: '#2fb344', bookmark: '#f76707', collection: '#ae3ec9',
	document: '#d63939', event: '#f59f00', location: '#0ca678', note: '#868e96', email: '#206bc4', page_view: '#868e96',
	entity: '#ffb400', owner: '#e03131', place: '#0ca678',
};

function graphNodeColor(n) {
	if (n.kind == 'entity') return n.owner ? graphColors.owner : (n.type == 'place' ? graphColors.place : graphColors.entity);
	return graphColors[n.classification] || '#868e96';
}

function graphNodeLabel(n) {
	if (n.kind == 'entity') return n.name || '(unnamed)';
	let meta = null;
	try { meta = n.metadata ? JSON.parse(n.metadata) : null; } catch {}
	if (n.text) return n.text.length > 28 ? n.text.slice(0, 28) + '…' : n.text;
	if (meta?.Kind == 'call') return `call (${meta.Direction || ''}${meta.Missed == true ? ', missed' : ''})`;
	if (meta?.Kind == 'system') return `system: ${meta.Event || ''}`;
	if (n.data_file) return n.data_file.split('/').pop();
	return `${n.classification || 'item'} #${n.id}`;
}

function graphNodeSub(n) {
	if (n.kind == 'entity') return n.owner ? 'you' : (n.type || 'entity');
	const when = n.timestamp ? DateTime.fromMillis(n.timestamp).toLocaleString(DateTime.DATE_SHORT) : '';
	return [n.classification, n.data_source, when].filter(Boolean).join(' · ');
}

// renderItemGraph draws the relationship graph around the item with a small force layout
// (no library): items and entities as nodes, relationships as labelled edges. Nodes can be
// dragged, clicked (opens the item/entity) and double-clicked (items: expand one more hop).
async function renderItemGraph(repoID, itemID) {
	const svg = $('#item-graph-svg');
	const NS = 'http://www.w3.org/2000/svg';
	const nodes = new Map(); // key -> node (+ x, y, vx, vy)
	const edges = new Map(); // id/key -> edge
	let seedKey = `item:${itemID}`;
	const W = () => svg.clientWidth || 800, H = () => svg.clientHeight || 420;

	function merge(g) {
		for (const n of g.nodes) {
			if (!nodes.has(n.key)) {
				// start new nodes near their first neighbour (or the centre)
				const anchor = [...nodes.values()].find(m => g.edges.some(e => (e.from == n.key && e.to == m.key) || (e.to == n.key && e.from == m.key)));
				nodes.set(n.key, {...n, x: (anchor?.x ?? W()/2) + (Math.random()-0.5)*80, y: (anchor?.y ?? H()/2) + (Math.random()-0.5)*80, vx: 0, vy: 0, expanded: false});
			}
		}
		for (const e of g.edges) {
			const k = e.id ? `r${e.id}` : `${e.from}|${e.to}|${e.label}`;
			if (!edges.has(k)) edges.set(k, e);
		}
		if (g.truncated) $('#item-graph-stats').title = 'graph truncated (node limit)';
	}

	const g = await app.ItemGraph({ repo: repoID, item_id: Number(itemID), depth: 2 });
	merge(g);
	const seed = nodes.get(seedKey);
	if (seed) { seed.x = W()/2; seed.y = H()/2; seed.expanded = true; }

	// ---- layout: springs along edges, repulsion between all nodes, gravity to the centre
	function step(alpha) {
		const arr = [...nodes.values()];
		for (let i = 0; i < arr.length; i++) {
			for (let j = i+1; j < arr.length; j++) {
				const a = arr[i], b = arr[j];
				let dx = b.x - a.x, dy = b.y - a.y;
				let d2 = dx*dx + dy*dy || 1;
				const f = 4000 / d2;
				const d = Math.sqrt(d2);
				dx /= d; dy /= d;
				a.vx -= dx*f*alpha; a.vy -= dy*f*alpha;
				b.vx += dx*f*alpha; b.vy += dy*f*alpha;
			}
		}
		for (const e of edges.values()) {
			const a = nodes.get(e.from), b = nodes.get(e.to);
			if (!a || !b) continue;
			const dx = b.x - a.x, dy = b.y - a.y;
			const d = Math.sqrt(dx*dx + dy*dy) || 1;
			const want = e.label == 'owner' ? 95 : 150;
			const f = (d - want) * 0.02 * alpha;
			a.vx += dx/d*f; a.vy += dy/d*f;
			b.vx -= dx/d*f; b.vy -= dy/d*f;
		}
		for (const n of arr) {
			n.vx += (W()/2 - n.x) * 0.002 * alpha;
			n.vy += (H()/2 - n.y) * 0.002 * alpha;
			if (n.fixed) { n.vx = n.vy = 0; continue; }
			n.vx *= 0.85; n.vy *= 0.85;
			n.x = Math.max(20, Math.min(W()-20, n.x + n.vx));
			n.y = Math.max(20, Math.min(H()-20, n.y + n.vy));
		}
	}

	// ---- drawing
	const layerEdges = document.createElementNS(NS, 'g');
	const layerLabels = document.createElementNS(NS, 'g');
	const layerNodes = document.createElementNS(NS, 'g');
	svg.replaceChildren(layerEdges, layerLabels, layerNodes);
	const defs = document.createElementNS(NS, 'defs');
	defs.innerHTML = `<marker id="graph-arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#999"/></marker>`;
	svg.prepend(defs);
	const els = new Map();

	function ensureElements() {
		for (const [k, e] of edges) {
			if (els.has('e'+k)) continue;
			const line = document.createElementNS(NS, 'line');
			line.classList.add('edge', e.label);
			if (e.directed && e.label != 'owner') line.setAttribute('marker-end', 'url(#graph-arrow)');
			layerEdges.append(line);
			const label = document.createElementNS(NS, 'text');
			label.classList.add('edge-label');
			label.setAttribute('text-anchor', 'middle');
			label.textContent = e.label + (e.value != null && e.value !== '' ? ` ${e.value}` : '');
			layerLabels.append(label);
			els.set('e'+k, {line, label});
		}
		for (const [k, n] of nodes) {
			if (els.has('n'+k)) continue;
			const gEl = document.createElementNS(NS, 'g');
			gEl.classList.add('node', n.kind);
			if (k == seedKey) gEl.classList.add('seed');
			const r = n.kind == 'entity' ? 14 : (k == seedKey ? 16 : 11);
			const circle = document.createElementNS(NS, 'circle');
			circle.setAttribute('r', r);
			circle.setAttribute('fill', graphNodeColor(n));
			gEl.append(circle);
			if (n.kind == 'entity') {
				const initials = document.createElementNS(NS, 'text');
				initials.setAttribute('text-anchor', 'middle'); initials.setAttribute('dy', '4');
				initials.setAttribute('fill', '#fff'); initials.style.fontSize = '10px'; initials.style.fontWeight = '600';
				initials.textContent = (n.name || '?').split(/\s+/).slice(0, 2).map(w => w[0]).join('').toUpperCase();
				gEl.append(initials);
			}
			const label = document.createElementNS(NS, 'text');
			label.setAttribute('text-anchor', 'middle'); label.setAttribute('dy', r + 13);
			label.textContent = graphNodeLabel(n);
			gEl.append(label);
			const sub = document.createElementNS(NS, 'text');
			sub.classList.add('node-sub');
			sub.setAttribute('text-anchor', 'middle'); sub.setAttribute('dy', r + 24);
			sub.textContent = graphNodeSub(n);
			gEl.append(sub);
			const title = document.createElementNS(NS, 'title');
			title.textContent = n.kind == 'entity' ? `${n.name} (${n.type}) #${n.id}` : `${n.classification} #${n.id}\n${n.text || n.data_file || ''}`;
			gEl.append(title);

			// interactions
			let dragged = false, startX, startY;
			gEl.addEventListener('pointerdown', ev => {
				ev.preventDefault(); dragged = false; startX = ev.clientX; startY = ev.clientY;
				n.fixed = true; gEl.setPointerCapture(ev.pointerId);
			});
			gEl.addEventListener('pointermove', ev => {
				if (!n.fixed) return;
				if (Math.abs(ev.clientX - startX) + Math.abs(ev.clientY - startY) > 3) dragged = true;
				const pt = svgPoint(ev); n.x = pt.x; n.y = pt.y; alpha = Math.max(alpha, 0.3);
			});
			gEl.addEventListener('pointerup', ev => {
				n.fixed = false; gEl.releasePointerCapture(ev.pointerId);
				if (dragged) return;
				if (ev.detail >= 2) return; // dblclick handles it
				clickTimer = setTimeout(() => {
					location.href = n.kind == 'entity' ? `/entities/${repoID}/${n.id}` : `/items/${repoID}/${n.id}`;
				}, 250);
			});
			gEl.addEventListener('dblclick', async ev => {
				clearTimeout(clickTimer);
				if (n.kind != 'item' || n.expanded) return;
				n.expanded = true;
				const more = await app.ItemGraph({ repo: repoID, item_id: n.id, depth: 1 });
				merge(more); ensureElements(); alpha = 1; updateStats();
			});
			layerNodes.append(gEl);
			els.set('n'+k, gEl);
		}
	}
	let clickTimer;
	function svgPoint(ev) {
		const rect = svg.getBoundingClientRect();
		return { x: ev.clientX - rect.left, y: ev.clientY - rect.top };
	}

	function draw() {
		for (const [k, e] of edges) {
			const el = els.get('e'+k); const a = nodes.get(e.from), b = nodes.get(e.to);
			if (!el || !a || !b) continue;
			// shorten the line so the arrow head ends at the target circle
			const dx = b.x - a.x, dy = b.y - a.y, d = Math.sqrt(dx*dx+dy*dy) || 1;
			const rb = b.kind == 'entity' ? 14 : 11, ra = a.kind == 'entity' ? 14 : 11;
			el.line.setAttribute('x1', a.x + dx/d*ra); el.line.setAttribute('y1', a.y + dy/d*ra);
			el.line.setAttribute('x2', b.x - dx/d*rb); el.line.setAttribute('y2', b.y - dy/d*rb);
			el.label.setAttribute('x', (a.x+b.x)/2); el.label.setAttribute('y', (a.y+b.y)/2 - 3);
		}
		for (const [k, n] of nodes) {
			els.get('n'+k)?.setAttribute('transform', `translate(${n.x},${n.y})`);
		}
	}
	function updateStats() {
		$('#item-graph-stats').textContent = `${nodes.size} nodes · ${edges.size} edges`;
		const kinds = new Map();
		for (const n of nodes.values()) {
			const k = n.kind == 'entity' ? (n.owner ? 'you' : n.type || 'entity') : n.classification;
			kinds.set(k, graphNodeColor(n));
		}
		$('#item-graph-legend').innerHTML = [...kinds].map(([k, c]) => `<span class="legend-dot" style="background:${c}"></span>${k}`).join('');
	}

	ensureElements(); updateStats();
	let alpha = 1;
	// settle the layout before the first paint, then animate the rest
	for (let i = 0; i < 120; i++) step(1);
	function frame() {
		if (!svg.isConnected) return;
		if (alpha > 0.01) { step(alpha); alpha *= 0.97; draw(); }
		requestAnimationFrame(frame);
	}
	draw();
	requestAnimationFrame(frame);
}
